### ISSUE TITLE
Enchance encodeForOS to auto-detect the underling OS

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#143] opened 2014-11-13 17:10 UTC
_From [manico.james@gmail.com](https://code.google.com/u/manico.james@gmail.com/) on July 26, 2010 16:48:03_

The encodeForOS function in the ESAPI for Java reference implementation should autodetect the OS, rather than require the caller to send in the type of OS to make it safe for. It should use the right codec automatically given the underlying OS, or throw some kind of notimplementedexception if it determines it’s on an OS that it doesn’t recognize (have an encoder for).

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=133_

**Comment by xeno6696** [comment] 2017-07-19 17:45
Hmm.  Can anyone retrieve Manico's patch?  @kwwall ?

**Comment by kwwall** [comment] 2017-07-20 02:47
@xeno6696 Yeah, I have all the patches from Google Code issues that were had corresponding GitHub issues that still open as of Feb 1, 2016. I will email all of them to you in a gzipped tarball.

**Comment by jeremiahjstacey** [comment] 2019-10-02 21:56
@xeno6696 @kwwall  I think this should be closed.  The issue is concerned with DefaultEncoder.encodeforOS.    It appears that method has been extended from taking only a String to taking the Codec and the String.  The only call in the baseline (non-test) is from the DefaultExecutor.  Looking at the constructor for the DefaultExecutor, it is already handling windows and unix systems:
```

 /**
     * Instantiate a new Executor
     */
    private DefaultExecutor() {
		if ( System.getProperty("os.name").indexOf("Windows") != -1 ) {
			logger.warning( Logger.SECURITY_SUCCESS, "Using WindowsCodec for Executor. If this is not running on Windows this could allow injection" );
			codec = new WindowsCodec();
		} else {
			logger.warning( Logger.SECURITY_SUCCESS, "Using UnixCodec for Executor. If this is not running on Unix this could allow injection" );
			codec = new UnixCodec();
		}
    }
```

Unless I'm misunderstanding, this issue is resolved by the strategy pattern codec from the DefaultExecutor and there is no additional work needed.

**Comment by xeno6696** [comment] 2019-10-04 02:52
I’m inclined to agree.  But maybe there should be a Linux check?

**Comment by kwwall** [comment] 2019-10-04 04:46
@xeno6696 The way that the code is written, it doesn't need a Linux check. The UmixCodec will work for Linux and the check is such that, if the OS is not Windows something or other, then the UnixCodec is used.

**Comment by kwwall** [comment] 2019-10-04 04:51
@jeremiahjstacey I'm in favor of closing this issue if we have a test for Windows and Unix (or Linux) that can confirm that it works as expected. That should be easy enough to implement if it doesn't already exist. I believe that it already works, but it never hurts to prove it.

**Comment by jeremiahjstacey** [comment] 2019-10-04 12:21
New tests added to verify that the ctr of the DefaultExecutor assigns the desired codec based on the system property value.

There are tests for the use of the codecs in both the Exectutor and Encoder test structures, so I don't believe that needed to be extended.

**Comment by jeremiahjstacey** [comment] 2019-10-12 10:21
Based on conversations previous, this issue should be resolved with previous changes in the DefaultExecutor.  Tests added in https://github.com/ESAPI/esapi-java-legacy/pull/520 confirm intended capability

**Closed by jeremiahjstacey** 2019-10-12 10:21 UTC
Labels: Component-Encoder, Milestone-Release2.0, Priority-Medium, enhancement, imported
