### ISSUE TITLE
Patch for /trunk/src/main/java/org/owasp/esapi/reference/crypto/JavaEncryptor.java

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#255] opened 2014-11-13 18:25 UTC
_From [noloa...@gmail.com](https://code.google.com/u/114558122492435650190/) on October 11, 2011 20:49:15_

Whitespace

**Attachment:** [JavaEncryptor.java.patch](http://code.google.com/p/owasp-esapi-java/issues/detail?id=248)

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=248_

**Comment by kwwall** [comment] 2018-08-16 03:26
I diff'd the two "repaired" patch files from this issue and issue #256 and confirmed that the 2 patch files are identical. Also confirmed that this is only whitespace cleanup.

Thus am closing this as a duplicate of #256 and leaving that open.

**Comment by kwwall** [comment] 2018-08-16 03:26
Okay... and this time I'll actually close it too! :)

**Closed by kwwall** 2018-08-16 03:26 UTC
Labels: Component-Encryptor, Maintainability, Milestone-Release2.1, OpSys-All, Priority-Low, Type-Patch, imported
