### ISSUE TITLE
Trust Boundary Violation - while triggering veracode

### ISSUE THREAD

**Issue by nidhinmp** [ESAPI/esapi-java-legacy#396] opened 2017-06-29 05:19 UTC
```
Enumeration params = req.getParameterNames();
                String sPrefix = "prefix_";
                while (params.hasMoreElements())
                {
                    String paramName = (String) params.nextElement();
                    if (paramName.startsWith(sPrefix))
                    {
                        String value = (Tool.getValue(req.getParameter(paramName)));
                        try {
                        session.setAttribute(ESAPI.validator().getValidInput("SafeCheckString",paramName,"SafeCheckString",1024,true), ESAPI.validator().getValidInput("SafeCheckString",value,"SafeCheckString",1024,true));//flaw
                        }
                        catch (ValidationException e) 
                        {
                            ServiceHandler.writeException("Validation Exception occured while validating Input",e);
                        } catch (IntrusionException e) 
                        {
                            ServiceHandler.writeException("Intrusion Exception  occured while validating Input",e);
                        }
                    }
                }
```

I'm getting trust boundary violation in the code (session.setAttribute(....) while triggering veracode.

How can I solve this.

Currently we have few trust boundary violation (CWE ID 501) flaws in our application. The recommended solution to fix this was to validate the input against a regex. Thus, we used ESAPI.validator.getValidInput() API. but the flaws are still not getting mitigated

**Comment by xeno6696** [comment] 2017-06-29 13:44
This isn't a bug against ESAPI, but your application.  Suggest you add the context I asked for to your SO question [here.  ](https://stackoverflow.com/questions/44794089/trust-boundary-violation-while-triggering-veracode)  Specifically, you need to tell the community HOW you're using those parameters.  Veracode is flagging it where you set them into the session because `request.getParameters()` is extremely dynamic the way you're using it... you're filtering on `"prefix_"` as opposed to pulling out an explicit variable which misdirects the static tool because it now cannot see what you're doing when you're using it later.  Remember that static analysis tools aren't usually smart enough to detect runtime logic like what you're doing here.  

As far as the common weakness, you need to understand that anything you pull from the request object is **_user controlled_** and therefore **untrusted** every single time it comes into the application.  Think of `request.getParameters()` as a publicly known global variable.  The "trust boundary" is that you're setting a user-controlled variable into the session object, and typically the session object should be reserved for items that **only the server should know.**  Also note that stuffing variables into a session object can cause memory leaks on a large enough application.  

The second half of this error is to determine all the places where those "_prefix" variables stored in your session are being used, and making sure that you're properly validating and sanitizing them.  If you have a whole bunch of these "_prefix" variables, I highly doubt that each one is important to application logic in exactly the same way.  You company hopefully has a Software Assurance expert running the Veracode platform that should be able to help you with anything more detailed than what I've given you here.  

This issue is not a bug against ESAPI.  Closing.

**Closed by xeno6696** 2017-06-29 13:44 UTC

**Comment by kwwall** [comment] 2017-07-02 04:28
@nidhinmp I agree 100% with @xeno6696 that this issue should be closed as this is not a bug against ESAPI, but just a quirk about how you are trying to use it. If you need further assistance, please post to the ESAPI-User mailing list. Thanks. -kevin
