### ISSUE TITLE
java.lang.ExceptionInInitializerError in 2.0 version

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#71] opened 2014-11-13 17:08 UTC
_From [lake...@gmail.com](https://code.google.com/u/108695746193399350146/) on November 23, 2009 21:07:54_

What steps will reproduce the problem? 1. Running a simple test found here: https://code.google.com/p/owasp-esapi-java/source/browse/trunk/src/test/java/org/owasp/esapi/reference/EncoderConcurrencyTest.java?spec=svn408&r=408 with new 2.0rc4 version. What is the expected output? What do you see instead? It should encode the javascript. I see this exception stack trace instead. What version of the product are you using? On what operating system? ESAPI-2.0-rc4.zip on Windows XP. Please provide any additional information below. Exception in thread "Thread-0" Exception in thread "Thread-1"
java.lang.Exceptio
nInInitializerError
        at EncoderConcurrencyTest.run(EncoderConcurrencyTest.java:19)
        at java.lang.Thread.run(Thread.java:595)
Caused by: java.lang.NullPointerException
        at java.util.Properties$LineReader.readLine(Properties.java:365)
        at java.util.Properties.load(Properties.java:293)
        at
org.owasp.esapi.reference.DefaultSecurityConfiguration.loadProperties
FromStream(DefaultSecurityConfiguration.java:370)
        at
org.owasp.esapi.reference.DefaultSecurityConfiguration.loadConfigurat
ion(DefaultSecurityConfiguration.java:507)
        at
org.owasp.esapi.reference.DefaultSecurityConfiguration.<init>(Default
SecurityConfiguration.java:207)
        at org.owasp.esapi.ESAPI.<clinit>(ESAPI.java:87)
        ... 2 more
java.lang.NoClassDefFoundError
        at EncoderConcurrencyTest.run(EncoderConcurrencyTest.java:19)
        at java.lang.Thread.run(Thread.java:595)

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=61_

**Comment by xeno6696** [comment] 2017-07-19 17:23
Had to have been fixed in the intervening years.  I cannot reproduce it.

**Closed by xeno6696** 2017-07-19 17:23 UTC
Labels: bug, Component-Logic, FirstBug, imported, Milestone-Release2.1, OpSys-All, Priority-Low, Usability

**Comment by kwwall** [comment] 2017-07-20 02:20
Bootstrapping the ESAPI logger related properties has long been an iffy proposition, but this probably got ixed when Manico rewrote the `DefaultSecurityConfiguration` class and since we never had a test case for it, no one (including myself) ever noticed it was fixed. Anyway, I'm good with closing it.
