### ISSUE TITLE
isValidDate fails to identify injection attack

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#258] opened 2014-11-13 18:25 UTC
_From [andrew.g...@gmail.com](https://code.google.com/u/107173630171124064388/) on November 07, 2011 08:28:17_

What steps will reproduce the problem? 1. Instantiate a SimpleDateFormat object called myFormat
2. Make a call to ESAPI.validator().dateIsValid using the following arguments: "datetest4", "September 11, 2001' union select \* from another_table where user_id like '&#37;", myFormat, false What is the expected output? What do you see instead? I think it's reasonable to expect the library to report "September 11, 2001' union select \* from another_table where user_id like '&#37;" as an invalid date; but, the method returns true. What version of the product are you using? On what operating system? I fetched the source from http://owasp-esapi-java.googlecode.com/svn/trunk , revision 1867 , compiled using the Oracle JDK 6 Standard Edition (build 1.6.0_24-b07) in Eclipse configured for J2SE-1.5 compliance. The host OS was Windows 7. Does this issue affect only a specified browser or set of browsers? No. Please provide any additional information below. I added the following line to org.owasp.esapi.reference.ValidatorTest.java at line 330:

assertFalse(instance.isValidDate("datetest4", "September 11, 2001' union select \* from another_table where user_id like '&#37;", format, false));

and this assertion fails.

I believe I have traced the root cause to org.owasp.esapi.reference.validation.DateValidationRule.java line 97:

return format.parse(canonical);

According to the JavaDoc for DateFormat.parse at http://download.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html#parse&#37;28java.lang.String,&#37;20java.text.ParsePosition&#37;29 , the parse method does not necessarily use up all characters to the end of the string. Thus the current implementation apparently reads to the end of the valid date and returns true, without checking whether additional characters are present.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=251_

**Comment by xeno6696** [comment] 2017-07-27 14:54
@kwwall, there are three issues here that are all related.  Going to close this and the other and work with the one I started last weekend.

**Comment by xeno6696** [comment] 2017-07-27 14:54
Duplicate of #299

**Closed by xeno6696** 2017-07-27 14:54 UTC
Labels: bug, duplicate, imported, Priority-Medium
