### ISSUE TITLE
canonicalize falsely recognizes HTML named entities

### ISSUE THREAD

**Issue by alnemo** [ESAPI/esapi-java-legacy#414] opened 2017-08-08 08:28 UTC
There is a problem appearing while canonicalizing a string that contains ampersands, for example "ExternalId=1&InternalId=2&Trader=true&Center=X&CurrentDate=0000"   
After passing through
String returnValue = ESAPI.encoder().canonicalize( value );
The result is this
"ExternalId=1∫ernalId=2™r=true¢er=X¤tDate=0000"
Despite not having semicolons some parts of the string are recognized as HTML named entities and converted to their symbol representation. Is that intentional?

**Comment by xeno6696** [comment] 2017-08-08 12:36
That's a known issue that will be resolved in the next release by providing
a new Encoder.getCanonicalizedURI. method.

As to being intentional it isn't, but it is actually a secure default even
if it is incorrect behavior.  Canonicalize has two main purposes

1.)  Detect mixed and multiple encoding.
2.)  provide a String that is safer to then process regexes against.

You're getting hit by 1.) because URI's are a complex data type (See
RFC-3986) and there is no way to distinguish a URL from any other standard
string.

**Comment by planetlevel** [comment] 2017-08-08 12:59
The underlying problem is that some browsers recognize HTML entities even without the semicolon. So we have a collision between encoding schemes that makes canonicalizatiin difficult.

**Comment by xeno6696** [comment] 2017-08-11 04:59
Duplicate of #376, and will be fixed in the next release.

**Closed by xeno6696** 2017-08-11 04:59 UTC
