### ISSUE TITLE
latest version of ESAPI 2.5.1.0 not working with spring boot 3.0, it gives classNotFound for javax.servlet.

### ISSUE THREAD

**Issue by dwhacker** [ESAPI/esapi-java-legacy#770] opened 2023-01-13 18:45 UTC
When using latest version of ESAPI 2.5.1.0, it gives classNotFound for javax.servlet.
As we know Spring boot 3.0 uses jakarta.servlet.
Will it be fixed in upcoming releases?

**Comment by kwwall** [comment] 2023-01-13 19:19
See discussion at:
https://github.com/ESAPI/esapi-java-legacy/discussions/768

**Comment by kwwall** [comment] 2023-01-14 00:20
This is a duplicate of issue #767 (which for the time-being is locked and replaced by the discussion #768). Therefore I am closing this issue as a duplicate.

**Closed by kwwall** 2023-01-14 00:20 UTC
Labels: duplicate, enhancement
