### ISSUE TITLE
Canonicalization might not be performed

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#234] opened 2014-11-13 18:25 UTC
_From [schulger...@widmann.de](https://code.google.com/u/108919803892695304578/) on May 25, 2011 05:43:27_

There's a bug in DefaultEncoder.canonicalize(String input).

It's supposed to use the settings
Encoder.AllowMultipleEncoding and
Encoder.AllowMixedEncoding
but it's effectively using
!Encoder.AllowMultipleEncoding and
!Encoder.AllowMixedEncoding

See lines 116-123:

public String canonicalize( String input ) {
                if ( input == null ) {
                        return null;
                }
                return canonicalize(input, 
                                                        ESAPI.securityConfiguration().getAllowMultipleEncoding(),
                                                        ESAPI.securityConfiguration().getAllowMixedEncoding() );
        }

It should be

public String canonicalize( String input ) {
                if ( input == null ) {
                        return null;
                }
                return canonicalize(input, 
                                                        !ESAPI.securityConfiguration().getAllowMultipleEncoding(),
                                                        !ESAPI.securityConfiguration().getAllowMixedEncoding() );
        }

because

canonicalize(String, boolean, boolean)

is defined as

canonicalize(String input, boolean restrictMultiple, boolean restrictMixed)

and not as

canonicalize(String input, boolean allowMultiple, boolean allowMixed)

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=226_

**Comment by xeno6696** [comment] 2016-06-14 12:42
@kwwall going to close this one.  While what the person says is true, I don't think its safe to reverse any boolean logic this far into the life of the API.

**Closed** 2016-06-14 12:42 UTC
Labels: bug, imported, Priority-Medium

**Comment by kwwall** [comment] 2016-06-14 17:06
At a minimum, perhaps some clarification in the Javadoc is in order then?
B/c it seems as though what we are saying is "yes, this probably is not the
intended behavior, but by now so many people may be relying on this broken
behavior that fixing it could have unintended consequences."

If we are going to change the actual behavior, we should at least document
what it is actually doing, don't you agree? Changing the names of the
formal parameters would be a good start. And maybe a "@see" to refer to
this bug report.

-kevin
