### ISSUE TITLE
Not able to turn off ESAPI logging

### ISSUE THREAD

**Issue by arpita012020** [ESAPI/esapi-java-legacy#594] opened 2021-02-17 10:42 UTC
My expectation is ESAPI will validate our request parameter . but should not print any log since some of my request parameters are PII data and I don't want it to be logged.
We are using JavaLogFactory for logging. Also made following change in esapi-java-logging.properties:
handlers= java.util.logging.ConsoleHandler
.level= OFF
java.util.logging.ConsoleHandler.level = OFF
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=[%1$tF %1$tT] [%3$-7s] %5$s %n
#https://www.logicbig.com/tutorials/core-java-tutorial/logging/customizing-default-format.html

But still it is printing logs since esapi-java-logging.properties file not being loaded at all.

We also tried commenting ESAPI.Logger in ESAPI.properties file. But it is taking JavaLogFactory as default logger.

Please help.

**Comment by kwwall** [comment] 2021-02-17 16:20
@arpita012020 - Here's a suggestion for a possible workaround that might work if you are running on any sort of *nix system... Try setting 'handlers' to 'java.util.logging.FileHandler' instead and then see if you can configure it to log to "/dev/nill".

**Comment by xeno6696** [comment] 2021-02-17 20:27
@kwwall I think you meant `dev/null`

**Comment by kwwall** [comment] 2021-02-17 23:56
@xeno6696 - LOL. SMH. But, I no longer are a UNIX system adminestrater, so I fergottin how to spel "null". :)
Absolutely, I meant `/dev/null`. Thanks for catching that.

**Comment by xeno6696** [comment] 2021-02-18 00:10
@arpita012020 -->  If you can put together a unit test that allows you to reproduce the problem (as suggested in the other version of this question) more folks could potentially help you.  Plus it would help you test any of the solutions suggested.  As it sits right now I find myself with free time but no context with which to help you.

**Comment by xeno6696** [comment] 2021-02-18 00:11
@kwwall at least you didn't do `dev/dill` which would have left everyone here in quite the pickle!  (^_^)

**Comment by jeremiahjstacey** [comment] 2021-02-18 00:15
I'll see what I can find/reproduce.
I will not the semi-concerning statement made in the initial description

> But still it is printing logs since esapi-java-logging.properties file not being loaded at all.

This would immediately imply that the file is not being correctly placed on the application path, and it may not be an issue with the library behavior.

**Comment by jeremiahjstacey** [comment] 2021-02-18 00:18
Quick look in the JavaLogFactory class would indicate that the java logging would not function if it does not find the configuration.  I think the statement I was concerned with is a non-issue.

If the esapi-java-logging.properites file is not found a ConfigurationException is thrown, so we would get significantly less logging from the library in that case.

**Comment by kwwall** [comment] 2021-02-18 00:22
@xeno6696 - Nice! But even _my_ finger farts are not _that_ bad.

**Comment by jeremiahjstacey** [comment] 2021-02-18 00:26
There is a chance this is working as designed.

I've set my logging to off, as described, and I'm debugging tests.  Most of the output is being filtered out; however, any call to the Esapi Logger.always method will always be printed. That content cannot be disabled (as is defined by always).

Watching other levels of info, warn, etc -- those are being prevented as desired.

**Comment by kwwall** [comment] 2021-02-18 00:38
@jeremiahjstacey - Yep, that's what I would predict. I didn't realize that we had any calls to Logger.ALL internal to the ESAPI code though (outside of our JUnit tests outside the logger code itself.

@arpita012020 -- You are going to have to tell us what ESAPI method you were calling that resulted in this unintended logging.

**Comment by kwwall** [comment] 2021-02-18 00:40
@jeremiahjstacey - Okay; I partially take that back. I do also see several calls to `logger.always()` in the `SecurityProviderLoader` class. It seems very doubtful that that is what @arpita012020 is complaining about though.

**Comment by jeremiahjstacey** [comment] 2021-02-18 00:43
I have to take that back....  even always isn't logging.

If you are interested in replicating my test, add a breakpoint in the method JavaLogBridgeImpl.log behavior.
https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/main/java/org/owasp/esapi/logging/java/JavaLogBridgeImpl.java

Note that the esapi level passed in is used to identify the java handler to use.  Before processing the message we check that the handler is enabled for the specified logger (this is the filter behavior).

If you update the esapi-java-logging.properties file under src/test/resources to set the levels to OFF, and then debug the full set of esapi tests you can see my results.
```
  @Override
    public void log(Logger logger, int esapiLevel, EventType type, String message) {
        JavaLogLevelHandler handler = esapiJavaLevelMap.get(esapiLevel);
        if (handler == null) {
            throw new IllegalArgumentException("Unable to lookup Java level mapping for esapi value of " + esapiLevel);
        }
        if (handler.isEnabled(logger)) {
            String fullMessage = appender.appendTo(logger.getName(), type, message);
            String cleanString = scrubber.cleanMessage(fullMessage);

            handler.log(logger, cleanString);
        }
    }
```

Adding a breakpoint to `handler.log(logger, cleanString)` never gets hit.  Ever.

**Comment by kwwall** [comment] 2021-02-18 00:47
@jeremiahjstacey wrote:
> I'll see what I can find/reproduce.
> I will not the semi-concerning statement made in the initial description
> 
> > But still it is printing logs since esapi-java-logging.properties file not being loaded at all.
> 
> This would immediately imply that the file is not being correctly placed on the application path, and it may not be an issue with the library behavior.

@jeremiahjstacey - I am wondering if @arpita012020 just made the comment that
> But still it is printing logs since esapi-java-logging.properties file not being loaded at all.

simply because setting  `java.util.logging.ConsoleHandler.level = OFF` did not disable logging as expected and therefore assumed that was the case.

**Comment by jeremiahjstacey** [comment] 2021-02-18 00:51
One more correction to my previous statement.  One test does trigger the block.  The test for the class, which is intended to verify the behavior of an instance of the JavaLogBridgeImpl that is not provided by the JavaLogFactory.  So it does trigger, but it's a different object and an isolated test scope so I excluded it from my consideration.   Apologies for that potentially confusing mis-information.

**Comment by jeremiahjstacey** [comment] 2021-02-18 01:10
I have confirmed that the design of always does not supersede off, as identified in the ESAPICustomJavaLevel enum.
https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/main/java/org/owasp/esapi/logging/java/ESAPICustomJavaLevel.java

```
/**
     * Defines a custom level that should result in content always being recorded, unless the Java Logging configuration is set to OFF.
     */
    public static final Level ALWAYS_LEVEL = new ESAPICustomJavaLevel( "ALWAYS", Level.OFF.intValue() - 1);
```

**Comment by jeremiahjstacey** [comment] 2021-02-18 01:15
Based on the aforementioned testing I cannot reproduce the problem state.  I will hold off on any further investigation or effort pending more specific context on how to replicate the issue.

**Comment by xeno6696** [comment] 2021-02-18 01:56
So in other words @jeremiahjstacey, you've done your best to recreate @arpita012020 's state, and everything appears to be nominal?

**Comment by jeremiahjstacey** [comment] 2021-02-18 03:24
@xeno6696 that is correct.  The library appears to be acting as desired, so far as I have been able to tell.

**Comment by kwwall** [comment] 2021-02-18 04:12
@jeremiahjstacey - is it possible that it just doesn't honor 'OFF' in order to disable it logging. Do we even have a for that? (I got lost in your discussion of 'ALWAYS' (i.e., Level.ALL). :-) As you indicated, LEVEL.OFF is not mapped to `levelLookup`. Maybe it is not something we ever considered as use case? What _is_ the proper way to disable logging?

**Comment by kwwall** [comment] 2021-02-18 04:18
@arpita012020 - I thought of something else to try. If you PII is only being logged when ESAPI throws an exception of some kind, then you could try setting `IntrusionDetector.Disable=false` in your **ESAPI.properties** file as many of the ESAPI exceptions subclass IntrusionException which causes logging. It may not work...it depends on what and why in ESAPI is doing the logging, but it might be worth a shot. (However, to get to the bottom of this, you need to provide us more details that were asked by the 3 of us at various times in the previous issue comments.)

**Comment by jeremiahjstacey** [comment] 2021-02-18 12:11
@kwwall 

**Summary** - The library does respect the Java level setting of OFF. The listed configuration of esapi-java-logging.properties is the correct method to disable the java logging.

I've tried to provide a summary below of why the system works as desired in the _Technical Breakdown_, and also point out the errors that I made in validation in _Explanation of Confusion_. 

Please let me know if my intent is unclear, or further elaboration would be desired.

----
**Technical Breakdown**

In the JavaLogBridgIml.log method, we are checking if the handler "isEnabled" for the given Logger.  That delegates to the JavaLogHander implementation which verifies that the Java Log level configured for that handler `isLoggable` in the Logger specified.
The implementation of `java.util.logger.Loggger.isLoggable(java.util.logging.Level)` is as follows:
 ```
  public boolean isLoggable(Level level) {
        if (level.intValue() < levelValue || levelValue == offValue) {
            return false;
        }
        return true;
    }
```

1. The Java Logger will filter out any java.util.logging.Level that has a numerical index less than the system configuration
2.  In the case where the system is configured to OFF, the numerical comparison is discarded, and the return will always be unloggable [`false`].

My comment on the configuration of the ESAPICustomJavaLevel.ALWAYS_LEVEL was intended to reference the implementation of `java.util.logging.Logger.isLoggable`, where our numerical index would return unloggable[`false`] for both logical conditions of the check since our value of ALWAYS_LEVEL is one less than the numerical value of the java.util.logging.Level.OFF.

Given this information, I see no functional way to replicate the error condition with the current information. 

----

**Explanation of Confusion**

I made a mistake in my testing while attempting to verify the behavior of OFF.   In my initial testing (described in previous comments), my breakpoint in the JavaLogBridgeImpl was triggered in the scope of the project tests.  In that case, the value of the ESAPI log level was always. In that one test, with those parameters I had seen that the JavaLogBridgeImpl did actually delegate the logging event to the Logger instance.

I assumed that this one case was the de-facto behavior, when it was actually the exception. The test that triggered the breakpoint was `JavaLogBridgeImplTest`.  This test was constructed to verify aspects of the JavaLogBridgeImpl may be tested consistently, regardless of the java logging configuration.

https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/test/java/org/owasp/esapi/logging/java/JavaLogBridgeImplTest.java

- Refer to the `setup` method and note that the java.util.logging.Logger is set up as a spy so that the default behavior can be changed for testing specific logic paths.
- See line 87 of the test, where the return of isLoggable is explicitly set to true.
- Line 89 is the one location in test execution that does delegate when the test-scope is configured to OFF (as a result of line 87)
- Also note that line 89 uses ESAPI logging level ALL which maps to the ESAPICustomJavaLevel.ALWAYS_LEVEL.

All these points are what led me down the path to explicitly verify that our implementation of ALWAYS_LEVEL acts as desired, and my comment noting that specific configuration.

**Comment by xeno6696** [comment] 2021-02-18 15:42
@arpita012020 So with settings you've given us, it's working fine.  The issue you're facing has to be with how you've configured ESAPI in your application.  I'd start by removing properties files to understand where/how your application is loading them, then once that's understood, debug logger initialization so you can figure out how your application is recieving logFactory configurations.  I'm closing this issue as this isn't a bug with esapi code, but you can feel free to poke us for troubleshooting advice as the discussion here isn't killed.

**Closed by xeno6696** 2021-02-18 15:42 UTC

**Comment by kwwall** [comment] 2021-02-19 19:03
@arpita012020 - Indeed I have tested this, and even with the log level set to 'ALWAYS', setting
`.level= OFF`
`java.util.logging.ConsoleHandler.level = OFF`
in **esapi-java-logging.propertie**s does indeed suppress the logging from ESAPI loggers (when JUL is used for logging that is).

Not only that, but I have also confirmed that this also suppresses logging that may come from an **IntrustionException**, even if the ESAPI Intrusion Detector is still enabled.

Therefore, I concur, that there is no bug here. Or at least we certainly have seen no evidence of such and thus I agree with @xeno6696 that you have some sort of configuration error. I would suggest running with a debugger and setting a breakpoint where you think the code is fail and then start single-stepping through the code. It probably is throwing a **ConfigurationException** that you are just not noticing.

If you respond with additional evidence that allows us to reproduce your problem, I will reopen this issue. Note however, if you just simply need assistance in configuration to get it to work, please share the details on the ESAPI Users Google group that is set up for that purpose. (You can find details about that Google Group in the ESAPI **README.md** file on GitHub.)
