### ISSUE TITLE
Could not initialize class org.owasp.esapi.reference.crypto.JavaEncryptor

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#273] opened 2014-11-13 18:26 UTC
_From [jgnan198...@gmail.com](https://code.google.com/u/114243376598290712568/) on March 14, 2012 10:58:39_

I'm using the esapi-2.0.1.jar from maven center, and encounter the following exception when trying to use the encryptor:

java.lang.NoClassDefFoundError: Could not initialize class org.owasp.esapi.reference.crypto.JavaEncryptor
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:169)
        at org.owasp.esapi.util.ObjFactory.make(ObjFactory.java:74)
        at org.owasp.esapi.ESAPI.encryptor(ESAPI.java:106)

The server we're using is tomcat 6. 

But, another instance running fine, with the same code and server configuration. I'm very curious about this issue and just want to know the reason why this happen so I want to open a ticket for the answer.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=266_

**Comment by kwwall** [comment] 2017-08-15 01:08
Unable to reproduce on Tomcat 7. But the submitter's own admission, this was working on at least one other instance with the same code and server configuration. To me, this sounds like it possibly could be a classpath problem or possibly a permission problem (e.g., unable to read the ESAPI jar file), but I can't tell because there is not enough information available.

Can whomever submitted this, add additional information to ensure this is reproducible? You didn't even say if on that one server where you were experiencing a problem if it was happening all the time or only on occasion.

**Comment by xeno6696** [comment] 2017-08-15 02:00
You're being very generous here Kevin... It's 5yrs old.  I would just close it saying as much.

**Comment by kwwall** [comment] 2017-08-15 04:50
Exactly, we've waited 5 years, so what's 5 more days or so? I put out a
call to the ESAPI-User mailing list. Give it a couple of days to see if it
gets a reply. If not, I'll close it at the end of the week.

**Comment by kwwall** [comment] 2017-08-19 05:23
Closing this as I've posted to ESAPI-User mailing list 4 days ago and have heard nothing back. Unable to reproduce and insufficient details to attempt to do so.

**Closed by kwwall** 2017-08-19 05:23 UTC
Labels: bug, imported, insufficient-info, Priority-Medium
